### ISSUE TITLE
config changes / rework / validation

### ISSUE THREAD

**Issue by c0rydoras** [adfinis/timedctl#95]
currently the config file includes just a few options, with these changes i propose something like the following:

## current config file
```toml
timed_url = "https://timed.example.com"
sso_client_id = "prod-example-timed"
sso_realm = "example"
sso_url = "https://sso.example.com"
```

## proposed config file (poc)
```toml
[timedctl]
version = "5.8.0" # changing this can result in broken config files
url = "https://timed.example.com" # url for a running frontend instance.

[oidc]
auth-path = "timedctl/auth"
auth-port = 5000 # this will always point to localhost as we have no other way to get the token

[oidc.generated] # these are automatically fetched based from timedctl.url
host = "https://sso.example.com/auth/realms/example/protocol/openid-connect"
clientId = "example-prod-timed"
authEndpoint = "/auth"
tokenEndpoint = "/token"
endSessionEndpoint = "/logout"
userinfoEndpoint = "/userinfo"
afterLogoutUri = "/"

[styles] # this could also be missing as it has a default
error = "bold red"
warning = "bold orange"
success = "bold green"

[styles.tables] # this would then be used something like this: Table(**{k.replace("-", "_") : v for k,v in styles.tables.items()}) but also have its own pydantic model to prevent wrong / unwanted options from being used and to set defaults.
box = "HEAVY_HEAD"
title-style = "bold"
```

the version would always be compared to the installed version and if something does not match or is missing, we would add it or transform the old scheme to match the new one. aditionally we would use `pydantic` to validate the config file to ensure nothing is missing or has the wrong file type.

## getting the OIDC settings from the frontend
parsing the OIDC settings from the frontend can be done like so:

```py
def fetch_config(url: str) -> dict:
    """
    Parse OIDC config from timed-frontend.

    Example:
    -------
        ```
        >>> fetch_config("https://timed.example.com")
        {
          "host": "https://sso.example.com/auth/realms/example/protocol/openid-connect",
          "clientId": "example-prod-timed",
          "authEndpoint": "/auth",
          "tokenEndpoint": "/token",
          "endSessionEndpoint": "/logout",
          "userinfoEndpoint": "/userinfo",
          "afterLogoutUri": "/"
        }
        ```
    """

    resp = get(url, timeout=1)
    environement = search(r'name="timed/config/environment" content="(.+)"', resp.text)
    oidc_config = unquote(environement)["ember-simple-auth-oidc"]
    return json.loads(oidc_config)
```

---

@gianklug what do you think about this
